eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

  server:
    eviction-interval-timer-in-ms: 1000

app:
  cors:
    allowedOrigins: http://localhost:3000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: wallet-service
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/wallet/**
        - id: oauth-service
          uri: lb://OAUTH-SERVICE
          predicates:
            - Path=/oauth/**
